### ISSUE TITLE
seems not to work in react-leaflet version 1.0.0-rc.3

### ISSUE THREAD

**Issue by barbalex** [Charmatzis/react-leaflet-bing#1]
I imported like this:

    import BingLayer from 'react-leaflet-bing'

and placed this in my Map component:

    <LayersControl>
      <LayersControl.BaseLayer name="Bing Aerial">
        <BingLayer
          bingkey="myBingKey"
        />
      </LayersControl.BaseLayer>
    </LayersControl>

then get this error:

    react-leaflet-bing.js?1d06:102Uncaught TypeError: Super expression must either be null or a function, not undefined(…)

Am I doing something wrong?

**Comment by Charmatzis** [comment]
I have updated to packages:
"react-leaflet": "^1.0.1"
"leaflet": "^1.0.2"
"react": "^15.4.1"

**Comment by barbalex** [comment]
hm. I now get:

    Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Karte`.

**Comment by Charmatzis** [comment]
Have you upgraded the node packages to that
"react-leaflet": "^1.0.1"
"leaflet": "^1.0.2"
"react": "^15.4.1"
versions?
Also try to add a BaseLayer first like that

```
 <BaseLayer checked name='Bing Maps Roads'>
              <BingLayer  bingkey={bing_key} type="Road"/>
   </BaseLayer>
```

**Comment by barbalex** [comment]
hey, thanks a lot for helping!

Yep, react is 15.4.1.
react-leaflet is 1.0.1
leaflet is 1.0.2
react-leaflet-bing is 2.0.0

I tried adding a base layer as you suggest.

I also tried adding BingLayer directly, without LayersControl.

I then tried importing BingLayer from an own component named BingAerial.js:

    import React from 'react'
    import BingLayer from 'react-leaflet-bing'

    const bingKey = `AjGOtB_ygBplpxXtKiiHtm-GERjSg9TFEoCmuBI_Yz4VWy0unRGUDo9GOZHA46Pf`

    const BingAerialLayer = () =>
      <BingLayer
        bingkey={bingKey}
        type="Road"
      />

    export default BingAerialLayer

into the map component:

    import React from 'react'
    import { Map } from 'react-leaflet'

    import BingAerial from './layers/BingAerial'

    class Karte extends React.Component {
      render() {
        const position = [47.295, 8.58]

        return (
          <Map
            center={position}
            zoom={13}
          >
            <BingAerial />
          </Map>
        )
      }
    }

    export default Karte

and get these errors:

    Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `BingAerialLayer`


    Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `BingAerialLayer`.
        at invariant (invariant.js:38)
        at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:68)
        at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:367)
        at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
        at Object.mountComponent (ReactReconciler.js:46)
        at Object.updateChildren (ReactChildReconciler.js:121)
        at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:208)
        at ReactDOMComponent._updateChildren (ReactMultiChild.js:312)
        at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
        at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:930)

where the last one seems to point directly to what BingLayer returns.

**Comment by Charmatzis** [comment]
can you send your code, so I can take a look?

**Comment by barbalex** [comment]
You can find it here: https://github.com/barbalex/apf/tree/master/app/components/Projekte/Karte

index.js does not load BingAerial because of the error that occurs.

BingAerial is called Aerial because I want to get it work with aerial instead of the road it is set to for testig.

When working on Bing map, I make indexWithBing.js to index.js so it runs when component Karte is loaded.

**Comment by Charmatzis** [comment]
I have done a pull request to your repo, plz check it out and se if it works....

**Comment by barbalex** [comment]
Unfortunately the exact same error persists :-(

Thanks for your effort!

I will try to reproduce this on CodePen or similar. Trouble is: I will probably struggle with the unfamiliar platform a lot. But I will try.

**Comment by barbalex** [comment]
omg

the solution is:

    import { BingLayer } from 'react-leaflet-bing'

instead of:

    import BingLayer from 'react-leaflet-bing'

Sorry for bugging you and thanks a lot for this great tool!

**Comment by Charmatzis** [comment]
Don't worry!!!!
