### ISSUE TITLE
compatibility with react v16

### ISSUE THREAD

**Issue by barbalex** [Charmatzis/react-leaflet-bing#4]
I updated to react v16.0.0.

react-leaflet-bing works like a charm.

When running `npm i` I get this message:

    npm WARN react-leaflet-bing@3.0.0 requires a peer of react@^15.5.0 but none is installed. You must install peer dependencies yourself.

As far as I understand the reason is here: https://github.com/Charmatzis/react-leaflet-bing/blob/master/package.json#L38

Do you require specific tests or can I create a pull request updating the peer dependency?

**Comment by Charmatzis** [comment]
I believe with that commit we are OK. 
https://github.com/Charmatzis/react-leaflet-bing/commit/ac84df1ee593e09185c8314fff6ba9f64d77cb9f
