### ISSUE TITLE
Custom map styles do not work

### ISSUE THREAD

**Issue by RobertWHurst** [Charmatzis/react-leaflet-bing#9]
Currently custom map styles are passed to bing when requesting the map metadata, but not when requesting the tiles, so the styles are not applied.

**Comment by agadeGF** [comment]
You probably already know this, but custom styling only works with type 'AerialWithLabelsOnDemand' and 'RoadOnDemand' :)

**Comment by RobertWHurst** [comment]
Oh fantastic. Thanks for getting back to me with that info. It might be good to update the readme with that info as it doesn't say that styles only work with those map types, and RoadOnDemand isn't even listed as a supported type.
